### PR TITLE
LEAN-3121: update registration route

### PR DESCRIPTION
**Pull request by mbetamony**
https://github.com/Atypon-OpenSource/manuscripts-api/blob/d01e0554304a1b30404cee981018080d7f9147a8/src/DomainServices/Auth/AuthService.ts#L293
In the code above,  we're generating a user token based on its connectID & some other props, but if a token is already there, we return it. Should we re-generate the token if we change the connectID? or maybe remove the connectID from the load when generating a token?
I'm also not sure if a decision has been made to merge this or not. @hhusban @mnatsheh

### CODE REVIEW

**Review by hhusban — APPROVED** [review]

**Comment by mnatsheh** [comment]
Good catch. Do we know why we even store the token? It seems better to always generate a token when logging in.

**Comment by mbetamony** [comment]
> Good catch. Do we know why we even store the token? It seems better to always generate a token when logging in.

I think we store for [AuthJWT strategy](https://github.com/Atypon-OpenSource/manuscripts-api/blob/0a6683b056618a54cde89e0bba3cea64b389bf80/src/Auth/Passport/JWT.ts#L36)

**Comment by mnatsheh** [comment]
We don't use that token for anything though.

**Comment by mbetamony** [comment]
Since we're not using the tokens saved in the DB, I have stopped saving them. One potential reason to keep the tokens could be to support refresh tokens.

A few notes:
1. I don't believe we're using the `login` route inside `AuthRoute`, the only way we login is using our `serverToServerTokenAuth` inside `AuthRoute` via the WM.
2. Tokens don't have an expiry date.
3. The frontend relies on GraphQL requests to obtain the editorAuthToken. It's unclear to me if this is necessary for `Connect`, if not, I suggest we move the login process to the frontend. This would make it easier to implement token expiry, support refresh tokens, and maybe introduce a logout option.

**Comment by mnatsheh** [comment]
The reason we do the login through WM is to simplify authentication across the system. If we don't do that, then the FE will need to authenticate to each service separately, which is a bit problematic.

**Review by mnatsheh — APPROVED** [review]
It looks like we're adding more data to the token than we need, but we can change that later.

**Pull request merged**
