### PR TITLE
LEAN-3366: Add replaceProject functionality to v2 of the api

### PR DESCRIPTION
**Pull request by mbetamony**

### CODE REVIEW

**Comment by mbetamony** [comment]
rerun

**Comment by mnatsheh** [comment]
@mbartenev-atypon @mbetamony can you provide an explanation for why this is needed? why couldn't we use the regular save endpoint?

**Comment by m-bartenev** [comment]
In v1, we always deleted all the models that weren't provided during bulkSave. That was the way we deleted models. Not sure what that was changed in V2 but FE relies on it because we don't communicate every deletion individually. I believe we don't need the previously used route for bulkUpdate and we can reconfigure that route instead of doing replace or just remove it.

**Comment by mbartenev-atypon** [comment]
In v1, we always deleted all the models that weren't provided during bulkSave. That was the way we deleted models. Not sure why that was changed in V2 but FE relies on it because we don't communicate every deletion individually. That was one of the reasons why we couldn't remove any content. I believe we don't need the previously used route for bulkUpdate and we can reconfigure that route instead of doing replace or just remove it.

**Comment by mnatsheh** [comment]
OK, I would say this is a bug with the v2 api; the save project api should delete any existing data. @mbetamony , can you file a ticket to fix that?

**Comment by mbetamony** [comment]
> OK, I would say this is a bug with the v2 api; the save project api should delete any existing data. @mbetamony , can you file a ticket to fix that?

Sure.

**Pull request merged**
