### PR TITLE
LEAN-2738: TCP-100C:  Authority

### PR DESCRIPTION
**Pull request by mbetamony**
@mbartenev-atypon, the backend is ready for testing, please let me know when you're done updating to latest master.

### CODE REVIEW

**Comment by mbetamony** [comment]
@mbartenev-atypon, @mnatsheh, @hhusban 
This is ready for review, it's also deployed on dev1 if you'd like to test it.

**Comment by mbetamony** [comment]
Can someone please review this?

**Review by mnatsheh — APPROVED** [review]
I'm not sure about the queuing part, it doesn't seem right, but since it's working I'll approve it for now and we can discuss later.

**Comment by mbetamony** [comment]
rerun

**Comment by mbetamony** [comment]
rerun

**Pull request merged**
