### PR TITLE
Cleanup to domain services and data access services 

### PR DESCRIPTION
**Pull request by mbetamony**
Some clarifications to simplify the reviewing process..
Don’t take a look at anything under tests now, i’ll be fixing as much as i can while this is being reviewed.
Most changes are deletions, so this isn’t as big as it looks.

Its most important to look at the things mentioned below.

### Data access

Everything’s been removed. The new implementation is based on [Prisma client extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions). We have an extender for each model, and a main Repository that’s responsible for extending. If you don’t prefer the idea of extensions and would like me to revert back to our old structure(prisma services, similar to how they were in quarterback) please let me know.

- I did some cleanup to the queries for the [Project Model](https://github.com/Atypon-OpenSource/manuscripts-api/pull/108/files#diff-0e768182738d6b4844b91577762cc25985a1e74ca1abca41862431a440aa7e9b)
- Removed Document History model, the steps are saved directly in the Document model, and each step has its clientID
- With extensions we don’t need to write any logic again for any query, take a look at the [authority service](https://github.com/Atypon-OpenSource/manuscripts-api/pull/108/files#diff-316ae0af783fbb077e1d59a5b35f1e95e1bd226a2b9283cb401c1e906ea22dd2) for this and point above. 

### Domain services

- ContainerService, SGService, DocumentHistory, SyncService, UserActivityTrackingService, ExpirationService have been removed.
- The functionality that was still used in ContainerService has been added to projectService
- CollaborationService has been renamed to AuthorityService
- DocumentService, and SnapshotService have been moved to DataAccess (as extensions)
- Introduced a new EventService that’s based on [Node.js Event Emitter](https://nodejs.org/api/events.html#class-eventemitter). I tried to keep it as simple as possible
- Database indexes are now done directly on the schema
- Changes above resulted in some changes to how we setup our DIContainer
- A new user and event models have been created
- The FE components are very reliant on MPUserProfile, i tried changing it there but it might be simpler for now if we return an object that’s similar to the UserProfile

### Migration

The way currently implement is based on this [documentation](https://www.prisma.io/docs/orm/prisma-migrate/workflows/data-migration) from Prisma, please take a look and let me know if we should find a better way to do this.

here are the scripts to patch the data: [document history](https://github.com/Atypon-OpenSource/manuscripts-api/pull/108/files#diff-7b174899b746850b54c1ff3017079eed3555d7552756588d0afa931b2f03c453), [user](https://github.com/Atypon-OpenSource/manuscripts-api/pull/108/files#diff-87ce80a236ee92b45d21c23e985db418d9c33b13aaad0cbe3d67b0fa036edc75). We’ll probably need a deployment code branch to run these scripts if we decide to go with this method.
I tested these locally and they’re working fine, if its okay i’d like to test them on one of our dev environments to make sure everything goes smoothly.
I’ll also make `connectUserID` and `email` unique once this is deployed everywhere and the scripts run successfully

### CODE REVIEW

**Comment by mnatsheh** [comment]
I don't have a problem with this way. A couple of comments based on a quick look at the code:
- The extenders use `static` extensively which I'm not a big fan of, especially since it's mixed with `this`. I also don't think we need functions that return functions for this.
- Is there still a need for `QuarterbackService`? can we merge it with `DocumentService`?
- What's the rational for renaming `CollaborationService` to `AuthorityService`?

**Comment by mbetamony** [comment]
> * The extenders use `static` extensively which I'm not a big fan of, especially since it's mixed with `this`. I also don't think we need functions that return functions for this.

Let's pretend that never happened
 
Alt Text

> * Is there still a need for QuarterbackService? can we merge it with DocumentService?

With the domain services cleanup there wasn't a need for the `DocumentService`, the `DocumentController` communicates directly with the document client(DB model); there weren't any need for extra functionality or a need for a service. But we can rename `QuarterbackService` to `DocumentService`. Or keep a service layer that just calls the client if you don't like the controller  communicating directly with the DB.

>* What's the rational for renaming CollaborationService to AuthorityService?

In PM, the [service](https://prosemirror.net/docs/guide/#collab) or api is referred to as the `authority`.

**Review by mnatsheh — APPROVED** [review]

**Review by hhusban — APPROVED** [review]

**Comment by mbetamony** [comment]
@mnatsheh Hello, a few notes based on our last call: 

1. concerning the version of the document, the version previously was calculated from the number of steps, and that's how its done in prosemirror's documentation
image
2. I added a script to `prisma migrate deploy` inside `package.json`, to run the scripts under [prisma/migrations/20240512160941_init/](https://github.com/Atypon-OpenSource/manuscripts-api/pull/108/files#diff-ee95e4ad2fa897a435432175949c7621bfae984405bcd4dd8e75c9321e1084c6)
3. once this is tested on a dev environment, its hard to go back to an older version of the api; we're deleting some data about users and changing their ids(i'll add this as a note to the QA).

Should we go ahead and move this to QA?

**Comment by mnatsheh** [comment]
What data are we deleting?

**Comment by mbetamony** [comment]
> What data are we deleting?



> What data are we deleting?

Any user row that doesn't start with `'User|' || 'User_'` (userStatus, userEmail, userEvent), but it won't work with previous versions because of the id change(the id change was to get rid of userIdForSync)
We can also query all the users to change back their ids  if necessary.

**Comment by mnatsheh** [comment]
Can't we keep the data in the User table as is? obviously any data created by the new code will not be usable by the old code, but shouldn't the old code still be able to function?

**Comment by mbetamony** [comment]
> Can't we keep the data in the User table as is? obviously any data created by the new code will not be usable by the old code, but shouldn't the old code still be able to function?

We can, but we'll have to maintain two ways of writing the userID (similar to what's done before, using userIDForSync). 
The issue is that even in our DB the userIDs are not consistent, in the projects its saved with this format: `User_`, and in the users table they're saved like this: `User|`. If we keep this now we'll probably have to keep it that way for a long time if not forever, let me know how you'd like me to handle it.

**Comment by mnatsheh** [comment]
It's fine, let's move ahead with this.

**Comment by mbetamony** [comment]
I might revert to using document history here, we're trying to deploy this on dev5 now, and we have around 839 documents there. Running the document script is going to take around 20-30 mins. What do you guys think? @mnatsheh @hhusban

**Comment by hhusban** [comment]
> I might revert to using document history here, we're trying to deploy this on dev5 now, and we have around 839 documents there. Running the document script is going to take around 20-30 mins. What do you guys think? @mnatsheh @hhusban
> 
> Edit: I actually don't think we need to move the steps, so nevermind, having the correct version should be enough

Why not execute a raw query like the following
`update test.public."ManuscriptDoc" set user_model_id = replace(user_model_id, '|', '_') `

**Comment by mbetamony** [comment]
> > I might revert to using document history here, we're trying to deploy this on dev5 now, and we have around 839 documents there. Running the document script is going to take around 20-30 mins. What do you guys think? @mnatsheh @hhusban
> > Edit: I actually don't think we need to move the steps, so nevermind, having the correct version should be enough
> 
> Why not execute a raw query like the following `update test.public."ManuscriptDoc" set user_model_id = replace(user_model_id, '|', '_') `

Do you mean running these scripts directly on the DB or to have a script file than runs these?

**Comment by hhusban** [comment]
> Do you mean running these scripts directly on the DB or to have a script file than runs these?
I'd say a script file

**Pull request merged**
